export default function () {
    return [
        {
            "id": 1,
            "group_name": "Fadeo",
            "users": 54,
            "admin": "Denise"
        }, {
            "id": 2,
            "group_name": "Quamba",
            "users": 58,
            "admin": "Amanda"
        }, {
            "id": 3,
            "group_name": "Mybuzz",
            "users": 48,
            "admin": "Dennis"
        }, {
            "id": 4,
            "group_name": "Edgewire",
            "users": 43,
            "admin": "Walter"
        }, {
            "id": 5,
            "group_name": "Mymm",
            "users": 24,
            "admin": "Mary"
        }, {
            "id": 6,
            "group_name": "Devpoint",
            "users": 22,
            "admin": "Larry"
        }, {
            "id": 7,
            "group_name": "Yoveo",
            "users": 76,
            "admin": "Joe"
        }, {
            "id": 8,
            "group_name": "Podcat",
            "users": 25,
            "admin": "Carolyn"
        }, {
            "id": 9,
            "group_name": "Wikibox",
            "users": 85,
            "admin": "Jennifer"
        }, {
            "id": 10,
            "group_name": "Kazu",
            "users": 100,
            "admin": "Justin"
        }, {
            "id": 11,
            "group_name": "Tanoodle",
            "users": 76,
            "admin": "Harold"
        }, {
            "id": 12,
            "group_name": "Dabfeed",
            "users": 25,
            "admin": "Anna"
        }, {
            "id": 13,
            "group_name": "Thoughtblab",
            "users": 74,
            "admin": "Sandra"
        }, {
            "id": 14,
            "group_name": "Gabcube",
            "users": 54,
            "admin": "Jeffrey"
        }, {
            "id": 15,
            "group_name": "Midel",
            "users": 10,
            "admin": "Katherine"
        }, {
            "id": 16,
            "group_name": "Youfeed",
            "users": 20,
            "admin": "Michelle"
        }, {
            "id": 17,
            "group_name": "Livefish",
            "users": 13,
            "admin": "Bruce"
        }, {
            "id": 18,
            "group_name": "Thoughtsphere",
            "users": 43,
            "admin": "Wayne"
        }, {
            "id": 19,
            "group_name": "Zoovu",
            "users": 44,
            "admin": "Timothy"
        }, {
            "id": 20,
            "group_name": "Fivespan",
            "users": 80,
            "admin": "Kenneth"
        }
    ]
}